import type { OsAppEvalTask, SurveyHarborTask, WebEvalTask } from "./types";

/** Static catalogs used when the API is unreachable or running an older backend. */
export const FALLBACK_WEB_TASKS: WebEvalTask[] = [
  {
    id: "web-playwright-quote-choice",
    title: "Quote choice (Playwright + live web)",
    siteName: "quotes.toscrape.com",
    siteUrl: "https://quotes.toscrape.com/",
    description: "Browse quotes.toscrape.com with Playwright and pick one quote worth saving or sharing.",
    taskPath: "application/tasks/example-web-playwright_quote-choice",
    outputArtifact: "quote_choice.json",
    submissionProfile: "quote_choice",
  },
  {
    id: "web-browser-use-laptop-choice",
    title: "Laptop shortlist (Browser-use)",
    siteName: "webscraper.io laptops",
    siteUrl: "https://webscraper.io/test-sites/e-commerce/static/computers/laptops",
    description: "Compare laptop listings with persona-browser-use and choose one realistic option.",
    taskPath: "application/tasks/example-web-browser-use_laptop-choice",
    outputArtifact: "laptop_choice.json",
    submissionProfile: "laptop_choice",
  },
  {
    id: "web-cocoa-plan-choice",
    title: "Plan preference (Cocoa)",
    siteName: "PythonAnywhere pricing",
    siteUrl: "https://www.pythonanywhere.com/pricing/",
    description: "Compare PythonAnywhere pricing plans with persona-cocoa and choose one realistic plan.",
    taskPath: "application/tasks/example-web-cocoa_plan-choice",
    outputArtifact: "plan_choice.json",
    submissionProfile: "plan_choice",
  },
  {
    id: "web-cua-bookshop-choice",
    title: "Bookshop choice (Docker CUA)",
    siteName: "books.toscrape.com",
    siteUrl: "https://books.toscrape.com/",
    description: "Browse books.toscrape.com with screenshot-based computer use in Docker and choose one book.",
    taskPath: "application/tasks/example-web-cua_bookshop-choice",
    outputArtifact: "book_interest.json",
    submissionProfile: "book_interest",
  },
];

export const FALLBACK_OS_APP_TASKS: OsAppEvalTask[] = [
  {
    id: "computer-use-linux-note-to-csv",
    title: "Computer Use Linux Note To Csv",
    platform: "linux",
    os: "linux",
    metaType: "os-app",
    domain: "software",
    difficulty: "easy",
    taskKind: "example",
    description: "Copy a short note into a CSV on a Linux desktop in Docker.",
    taskPath: "application/tasks/example-computer-use-linux_note-to-csv",
    outputArtifact: "decision.json",
    environmentLabel: "Docker Xvfb · persona-computer-1",
    osAppBackend: "docker",
  },
  {
    id: "computer-use-macos-calendar-reminder-handoff",
    title: "Computer Use Macos Calendar Reminder Handoff",
    platform: "macos",
    os: "macos",
    metaType: "os-app",
    domain: "software",
    difficulty: "easy",
    taskKind: "example",
    description: "Cross-app handoff between Calendar and Reminders on macOS via use.computer.",
    taskPath: "application/tasks/example-computer-use-macos_calendar-reminder-handoff",
    outputArtifact: "decision.json",
    environmentLabel: "use.computer · persona-computer-1",
    osAppBackend: "macos",
  },
  {
    id: "computer-use-ios-photo-access-review",
    title: "Computer Use Ios Photo Access Review",
    platform: "ios",
    os: "ios",
    metaType: "os-app",
    domain: "software",
    difficulty: "easy",
    taskKind: "example",
    description: "Review photo privacy settings on iOS Simulator via use.computer.",
    taskPath: "application/tasks/example-computer-use-ios_photo-access-review",
    outputArtifact: "decision.json",
    environmentLabel: "use.computer iOS · persona-computer-1",
    osAppBackend: "ios",
  },
  {
    id: "os-app-macos-shortcuts-gallery-picks",
    title: "Shortcuts Gallery Picks",
    platform: "macos",
    os: "macos",
    metaType: "os-app",
    domain: "software",
    difficulty: "medium",
    taskKind: "task",
    description: "Browse the Shortcuts Gallery on macOS and pick three shortcuts that best fit your needs.",
    taskPath: "application/tasks/os-app-macos_shortcuts-gallery-picks",
    outputArtifact: "picks.json",
    environmentLabel: "use.computer · persona-computer-1",
    osAppBackend: "macos",
  },
  {
    id: "os-app-macos-stocks-mu-sentiment",
    title: "Stocks: MU Sentiment",
    platform: "macos",
    os: "macos",
    metaType: "os-app",
    domain: "finance",
    difficulty: "medium",
    taskKind: "task",
    description: "Research Micron Technology (MU) in the Stocks app — review chart trends and news, then report your buy/sell/hold sentiment.",
    taskPath: "application/tasks/os-app-macos_stocks-mu-sentiment",
    outputArtifact: "sentiment.json",
    environmentLabel: "use.computer · persona-computer-1",
    osAppBackend: "macos",
  },
];

/** @deprecated Use FALLBACK_OS_APP_TASKS */
export const FALLBACK_CUA_TASKS = FALLBACK_OS_APP_TASKS;

export const FALLBACK_SURVEY_HARBOR_TASKS: SurveyHarborTask[] = [
  {
    id: "harbor-survey-product-attitudes",
    title: "Product Attitudes",
    description: "A short product-concept survey completed directly by the simulated persona respondent.",
    taskPath: "application/tasks/survey_product-attitudes",
    instrumentId: "product_attitudes_v1",
    surveyKind: "contributing",
  },
  {
    id: "harbor-survey-product-feedback",
    title: "Survey Product Feedback",
    description: "Product concept and pricing survey (FocusLoop).",
    taskPath: "application/tasks/example-survey_product-feedback",
    instrumentId: "product_feedback_v1",
    surveyKind: "example",
  },
  {
    id: "harbor-survey-claude-code-vscode-checkpoints",
    title: "Claude Code IDE Autonomy Survey",
    description: "Survey reactions to Claude Code's native VS Code extension and checkpoint feature.",
    taskPath: "application/tasks/survey_claude-code-vscode-checkpoints",
    instrumentId: "software_claude_code_vscode_checkpoints_v1",
    surveyKind: "contributing",
  },
  {
    id: "harbor-survey-robinhood-cortex-digests",
    title: "Robinhood Cortex Digests Survey",
    description: "Survey reactions to Robinhood Cortex Digests for stocks and crypto.",
    taskPath: "application/tasks/survey_robinhood-cortex-digests",
    instrumentId: "finance_robinhood_cortex_digests_v1",
    surveyKind: "contributing",
  },
  {
    id: "harbor-survey-cvs-prescription-ai",
    title: "CVS Health App Prescription AI Survey",
    description: "Survey reactions to the CVS Health app's conversational pharmacy assistant.",
    taskPath: "application/tasks/survey_cvs-prescription-ai",
    instrumentId: "healthcare_cvs_app_prescription_ai_v1",
    surveyKind: "contributing",
  },
  {
    id: "harbor-survey-nike-air-max-dn",
    title: "Nike Air Max Dn Dynamic Air Purchase Survey",
    description: "Survey reactions to Nike Air Max Dn Dynamic Air cushioning.",
    taskPath: "application/tasks/survey_nike-air-max-dn",
    instrumentId: "commerce_nike_air_max_dn_dynamic_air_v1",
    surveyKind: "contributing",
  },
];
