#!/usr/bin/env python3
"""Sample personas and write a multi-trial Harbor job YAML for application tasks."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml

from matraix.application_job import build_application_job_config
from matraix.persona_job import DEFAULT_DATASET, parse_stratify_field_args

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_JOBS_DIR = REPO_ROOT / "configs" / "jobs" / "application-task-job-recipe"


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "application-job"


def _default_job_name(
    *,
    task: str,
    stratify_fields: list[str],
    sample_size: int,
) -> str:
    task_slug = _slug(Path(task).name)
    if stratify_fields:
        dim_slug = "-".join(_slug(field.split(".")[-1]) for field in stratify_fields)
        return f"{task_slug}-{dim_slug}-n{sample_size}"
    return f"{task_slug}-n{sample_size}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--task",
        required=True,
        help="Application task path (e.g. application/tasks/example-survey_product-feedback)",
    )
    parser.add_argument(
        "--sample-size",
        type=int,
        default=1,
        help="Number of personas / trials (default: 1)",
    )
    parser.add_argument(
        "--stratify",
        action="append",
        default=[],
        metavar="FIELD",
        help=(
            "Stratify sampling by persona field(s). Repeat or comma-separate. "
            "Default: random sample from the pool (no stratification). "
            "Pass --stratify to balance across field values."
        ),
    )
    parser.add_argument(
        "--no-stratify",
        action="store_true",
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "--dataset",
        default=DEFAULT_DATASET,
        help=f"Persona dataset directory (default: {DEFAULT_DATASET})",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--name",
        default=None,
        help="Job basename for output YAML (default: derived from task + stratify fields)",
    )
    parser.add_argument(
        "--job-name",
        default=None,
        help="Harbor job_name / jobs/<job_name>/ directory (default: same as --name)",
    )
    parser.add_argument("--agent-name", default="persona-claude-code")
    parser.add_argument("--model-name", default="anthropic/claude-sonnet-4-6")
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output job YAML (default: configs/jobs/application-task-job-recipe/<name>.yaml)",
    )
    args = parser.parse_args()

    explicit_stratify = parse_stratify_field_args(args.stratify)
    if explicit_stratify:
        stratify_fields = explicit_stratify
    else:
        stratify_fields = []

    job_slug = args.name or _default_job_name(
        task=args.task,
        stratify_fields=stratify_fields,
        sample_size=args.sample_size,
    )
    job_name = args.job_name or job_slug

    spec = {
        "name": job_slug,
        "stratify_fields": stratify_fields,
        "sample_size": args.sample_size,
        "seed": args.seed,
        "persona_pool": args.dataset,
        "task": args.task,
        "agent": {
            "name": args.agent_name,
            "model_name": args.model_name,
        },
        "job": {
            "job_name": job_name,
            "jobs_dir": "jobs",
            "n_attempts": 1,
            "n_concurrent_trials": 1,
            "timeout_multiplier": 1.0,
            "environment": {"type": "docker", "delete": True},
        },
    }

    job_config = build_application_job_config(spec, repo_root=REPO_ROOT)
    meta = job_config.pop("_job_meta")

    out_path = args.out
    if out_path is None:
        DEFAULT_JOBS_DIR.mkdir(parents=True, exist_ok=True)
        out_path = DEFAULT_JOBS_DIR / f"{job_slug}.yaml"
    elif not out_path.is_absolute():
        out_path = REPO_ROOT / out_path
    out_path.parent.mkdir(parents=True, exist_ok=True)

    stratify_line = (
        ", ".join(stratify_fields) if stratify_fields else "none (random sample)"
    )
    header = (
        f"# Generated by application/scripts/generate_application_job.py\n"
        f"# Task: {args.task}\n"
        f"# Stratify: {stratify_line} | "
        f"sample={meta['sample_size']} from pool={meta['matched_pool_size']} | "
        f"seed={meta['seed']}\n"
        f"# Personas: {', '.join(meta['selected_persona_ids'])}\n"
        f"#\n"
        f"#   uv run harbor run -c {out_path.relative_to(REPO_ROOT)}\n\n"
    )
    out_path.write_text(
        header + yaml.safe_dump(job_config, sort_keys=False),
        encoding="utf-8",
    )

    sidecar = out_path.with_suffix(".meta.json")
    sidecar.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")

    print(f"Matched {meta['matched_pool_size']} personas; selected {meta['sample_size']}")
    print(f"Job: {out_path}")
    print(f"Meta: {sidecar}")
    print(f"Run: uv run harbor run -c {out_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
