"""Generate the 351-task synthetic chatbot batch Harbor job YAML."""
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
TASKS_DIR = REPO_ROOT / "application" / "tasks"
PERSONA_POOL = REPO_ROOT / "persona" / "datasets" / "bench-dev-sample"
OUTPUT = Path(__file__).resolve().parent / "pg-synthetic-351-full-batch.yaml"

DEFAULT_PERSONAS = ["0053", "0031", "0069", "0066", "0064", "0054"]

MODEL = "deepseek/deepseek-v4-flash"
N_CONCURRENT = 3


def main():
    persona_ids = DEFAULT_PERSONAS
    for pid in persona_ids:
        p = PERSONA_POOL / f"persona_{pid}.yaml"
        if not p.exists():
            print(f"Persona {pid} not found at {p}", file=sys.stderr)
            sys.exit(1)

    task_dirs = sorted([
        d for d in TASKS_DIR.iterdir()
        if d.is_dir() and d.name.endswith("_chatbot")
        and not d.name.startswith("example-")
    ])

    if len(task_dirs) < 351:
        print(f"Warning: found only {len(task_dirs)} chatbot tasks (expected 351+)",
              file=sys.stderr)
    elif len(task_dirs) > 351:
        print(f"Note: found {len(task_dirs)} tasks (including examples excluded={len(task_dirs)-351})",
              file=sys.stderr)

    agents = []
    for pid in persona_ids:
        agents.append({
            "name": "persona-user-sim",
            "model_name": MODEL,
            "kwargs": {
                "persona_path": f"persona/datasets/bench-dev-sample/persona_{pid}.yaml"
            }
        })

    tasks = [{"path": f"application/tasks/{d.name}"} for d in task_dirs]

    lines = [
        "# Generated by generate_351_batch_yaml.py",
        "# Full 351-task synthetic chatbot batch for PR #255",
        f"# Model: {MODEL}",
        f"# Persona pool: persona/datasets/bench-dev-sample",
        f"# Personas: {', '.join(persona_ids)}",
        f"# Tasks: {len(tasks)}",
        f"# Total trials: {len(tasks) * len(persona_ids)}",
        f"# n_concurrent_trials: {N_CONCURRENT} (conservative to avoid DeepSeek rate limits)",
        "",
        f"job_name: pg-synthetic-351-full-batch",
        f"jobs_dir: jobs",
        f"n_attempts: 1",
        f"timeout_multiplier: 1.0",
        f"n_concurrent_trials: {N_CONCURRENT}",
        f"quiet: false",
        "environment:",
        "  type: host",
        "  delete: true",
        "agents:",
    ]

    for a in agents:
        lines.append(f"- name: {a['name']}")
        lines.append(f"  model_name: {a['model_name']}")
        lines.append("  kwargs:")
        lines.append(f"    persona_path: {a['kwargs']['persona_path']}")

    lines.append("tasks:")
    for t in tasks:
        lines.append(f"- path: {t['path']}")

    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"Generated {len(tasks)} tasks x {len(persona_ids)} personas = "
          f"{len(tasks) * len(persona_ids)} total trials")
    print(f"Output: {OUTPUT}")


if __name__ == "__main__":
    main()
